spring.datasource.url=jdbc:postgresql://ep-jolly-firefly-a50h9phj-pooler.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_HEWKA7nQG1BO&sslmode=require&channelBinding=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chalakutev@gmail.com
spring.mail.password=uzsc rogb cjrv zotz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080