spring.datasource.url=jdbc:postgresql://ep-jolly-firefly-a50h9phj-pooler.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_HEWKA7nQG1BO&sslmode=require&channelBinding=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080