spring.datasource.url=postgresql://neondb_owner:npg_F5chkyNPTW8q@ep-jolly-firefly-a50h9phj-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=Radostin Chalakutev
spring.datasource.password=npg_F5chkyNPTW8q@ep

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080