app.client.name=FootballXtreme
app.client.short-name=FootballXtreme

app.client.phone=
app.client.email=
app.client.address=

app.client.language=bg
app.client.currency=BGN

app.booking.opening-time=09:00
app.booking.closing-time=23:00

app.booking.duration-1=60
app.booking.duration-2=90